=== TIBCOSoftware/sonar-bw/src/test/resources/xsd/shiporder.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.tibco.com/utils/wrapper/jaxb/tests"
	targetNamespace="http://www.tibco.com/utils/wrapper/jaxb/tests">

	<xs:simpleType name="string">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="int">
		<xs:restriction base="xs:positiveInteger" />
	</xs:simpleType>

	<xs:simpleType name="dec">
		<xs:restriction base="xs:decimal" />
	</xs:simpleType>

	<xs:simpleType name="orderId">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{6}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="shipTo">
		<xs:sequence>
			<xs:element name="name" type="tns:string" />
			<xs:element name="address" type="tns:string" />
			<xs:element name="city" type="tns:string" />
			<xs:element name="country" type="tns:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="item">
		<xs:sequence>
			<xs:element name="title" type="tns:string" />
			<xs:element name="note" type="tns:string" minOccurs="0" />
			<xs:element name="quantity" type="tns:int" />
			<xs:element name="price" type="tns:dec" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="shipOrder">
		<xs:sequence>
			<xs:element name="orderPerson" type="tns:string" />
			<xs:element name="shipTo" type="tns:shipTo" />
			<xs:element name="item" maxOccurs="unbounded" type="tns:item" />
		</xs:sequence>
		<xs:attribute name="orderId" type="tns:orderId" use="required" />
	</xs:complexType>

	<xs:element name="shipOrder" type="tns:shipOrder" />

</xs:schema>

=== TIBCOSoftware/sonar-bw/src/test/resources/xml/shipOrder1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:shipOrder orderId="123456"
	xmlns:tns="http://www.tibco.com/utils/wrapper/jaxb/tests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tibco.com/utils/wrapper/jaxb/tests ../xsd/shiporder.xsd ">
	<orderPerson>foo</orderPerson>
	<shipTo>
		<name>bar</name>
		<address>address</address>
		<city>city</city>
		<country>country</country>
	</shipTo>
	<item>
		<title>title</title>
		<note>note</note>
		<quantity>1</quantity>
		<price>0.0</price>
	</item>
</tns:shipOrder>
